"""fix still_path in tmdb_episodes

Revision ID: 02fe1ea0d62c
Revises: 3a87b89f56d8
Create Date: 2026-09-27 03:44:02.019473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fe1ea0d62c'
down_revision: Union[str, Sequence[str], None] = '3a87b89f56d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    op.add_column('tmdb_episodes', sa.Column('still_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmdb_episodes', 'still_path')
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
