"""Add trackers

Revision ID: 047f9fbf7030
Revises: m2n3o4p5q6r7
Create Date: 2026-09-17 20:24:10.440574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '047f9fbf7030'
down_revision: Union[str, Sequence[str], None] = 'm2n3o4p5q6r7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_tv_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tmdb_status', sa.String(length=50), nullable=True),
    sa.Column('total_seasons', sa.Integer(), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('first_air_date', sa.Date(), nullable=True),
    sa.Column('last_air_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_tv_series_status'), 'tracker_tv_series', ['status'], unique=False)
    op.create_index(op.f('ix_tracker_tv_series_tmdb_id'), 'tracker_tv_series', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_tracker_tv_series_user_id'), 'tracker_tv_series', ['user_id'], unique=False)
    op.create_table('tracker_tv_episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['tracker_tv_series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_tv_episodes_series_id'), 'tracker_tv_episodes', ['series_id'], unique=False)
    op.create_index(op.f('ix_tracker_tv_episodes_user_id'), 'tracker_tv_episodes', ['user_id'], unique=False)
    op.create_index(op.f('ix_tracker_tv_episodes_watched'), 'tracker_tv_episodes', ['watched'], unique=False)
    op.create_table('tracker_tv_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('character', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['tracker_tv_series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_tv_quotes_series_id'), 'tracker_tv_quotes', ['series_id'], unique=False)
    op.create_index(op.f('ix_tracker_tv_quotes_user_id'), 'tracker_tv_quotes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    op.drop_index(op.f('ix_feedback_reports_status'), table_name='feedback_reports')
    op.drop_index(op.f('ix_feedback_reports_user_id'), table_name='feedback_reports')
    op.drop_table('feedback_reports')
    op.alter_column('shopping_lists', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_lists', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_table('feedback_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=50), server_default=sa.text("'bug'::character varying"), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('steps_to_reproduce', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_route', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('error_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('screenshot_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=False),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('feedback_reports_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_reports_pkey'))
    )
    op.create_index(op.f('ix_feedback_reports_user_id'), 'feedback_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_reports_status'), 'feedback_reports', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_tracker_tv_quotes_user_id'), table_name='tracker_tv_quotes')
    op.drop_index(op.f('ix_tracker_tv_quotes_series_id'), table_name='tracker_tv_quotes')
    op.drop_table('tracker_tv_quotes')
    op.drop_index(op.f('ix_tracker_tv_episodes_watched'), table_name='tracker_tv_episodes')
    op.drop_index(op.f('ix_tracker_tv_episodes_user_id'), table_name='tracker_tv_episodes')
    op.drop_index(op.f('ix_tracker_tv_episodes_series_id'), table_name='tracker_tv_episodes')
    op.drop_table('tracker_tv_episodes')
    op.drop_index(op.f('ix_tracker_tv_series_user_id'), table_name='tracker_tv_series')
    op.drop_index(op.f('ix_tracker_tv_series_tmdb_id'), table_name='tracker_tv_series')
    op.drop_index(op.f('ix_tracker_tv_series_status'), table_name='tracker_tv_series')
    op.drop_table('tracker_tv_series')
    # ### end Alembic commands ###
