"""Add social domain and user preferences

Revision ID: 189c36cbe774
Revises: a282ff0494d6
Create Date: 2026-09-21 11:59:51.006046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '189c36cbe774'
down_revision: Union[str, Sequence[str], None] = 'a282ff0494d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_requester_addressee')
    )
    op.create_index(op.f('ix_friendships_addressee_id'), 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    op.create_index(op.f('ix_friendships_status'), 'friendships', ['status'], unique=False)
    op.alter_column('feedback_reports', 'report_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('feedback_reports', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('feedback_reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('feedback_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('default_startup_page', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('module_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'module_preferences')
    op.drop_column('users', 'default_startup_page')
    op.drop_column('users', 'profile_picture_url')
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('feedback_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('feedback_reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'new'::character varying"),
               existing_nullable=False)
    op.alter_column('feedback_reports', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=False)
    op.alter_column('feedback_reports', 'report_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'bug'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_friendships_status'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_addressee_id'), table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
