"""Add TV Series trackers domain

Revision ID: 1a169030e611
Revises: 189c36cbe774
Create Date: 2026-09-22 13:43:59.884612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a169030e611'
down_revision: Union[str, Sequence[str], None] = '189c36cbe774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmdb_series',
    sa.Column('tmdb_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('tmdb_status', sa.String(length=50), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('networks', sa.String(length=255), nullable=True),
    sa.Column('creators', sa.String(length=255), nullable=True),
    sa.Column('total_seasons', sa.Integer(), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('first_air_date', sa.Date(), nullable=True),
    sa.Column('last_air_date', sa.Date(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_table('tmdb_episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_tmdb_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['series_tmdb_id'], ['tmdb_series.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tmdb_episodes_series_tmdb_id'), 'tmdb_episodes', ['series_tmdb_id'], unique=False)
    op.create_table('user_series_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_tmdb_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_poster_path', sa.String(length=255), nullable=True),
    sa.Column('custom_backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('review_visibility', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_tmdb_id'], ['tmdb_series.tmdb_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_series_tracking_series_tmdb_id'), 'user_series_tracking', ['series_tmdb_id'], unique=False)
    op.create_index(op.f('ix_user_series_tracking_status'), 'user_series_tracking', ['status'], unique=False)
    op.create_index(op.f('ix_user_series_tracking_user_id'), 'user_series_tracking', ['user_id'], unique=False)
    op.create_table('user_episode_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_visibility', sa.String(length=50), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['tmdb_episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_episode_tracking_episode_id'), 'user_episode_tracking', ['episode_id'], unique=False)
    op.create_index(op.f('ix_user_episode_tracking_user_id'), 'user_episode_tracking', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tracker_tv_episodes_series_id'), table_name='tracker_tv_episodes')
    op.drop_index(op.f('ix_tracker_tv_episodes_user_id'), table_name='tracker_tv_episodes')
    op.drop_index(op.f('ix_tracker_tv_episodes_watched'), table_name='tracker_tv_episodes')
    op.drop_table('tracker_tv_episodes')
    op.drop_index(op.f('ix_tracker_tv_series_status'), table_name='tracker_tv_series')
    op.drop_index(op.f('ix_tracker_tv_series_tmdb_id'), table_name='tracker_tv_series')
    op.drop_index(op.f('ix_tracker_tv_series_user_id'), table_name='tracker_tv_series')
    
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    op.add_column('tracker_tv_quotes', sa.Column('episode_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tracker_tv_quotes_series_id'), table_name='tracker_tv_quotes')
    op.create_index(op.f('ix_tracker_tv_quotes_episode_id'), 'tracker_tv_quotes', ['episode_id'], unique=False)
    op.drop_constraint('tracker_tv_quotes_series_id_fkey', 'tracker_tv_quotes', type_='foreignkey')
    op.create_foreign_key(None, 'tracker_tv_quotes', 'tmdb_episodes', ['episode_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tracker_tv_quotes', 'character')
    op.drop_column('tracker_tv_quotes', 'series_id')
    
    op.drop_table('tracker_tv_series')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_tv_quotes', sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tracker_tv_quotes', sa.Column('character', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tracker_tv_quotes', type_='foreignkey')
    op.create_foreign_key(op.f('tracker_tv_quotes_series_id_fkey'), 'tracker_tv_quotes', 'tracker_tv_series', ['series_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tracker_tv_quotes_episode_id'), table_name='tracker_tv_quotes')
    op.create_index(op.f('ix_tracker_tv_quotes_series_id'), 'tracker_tv_quotes', ['series_id'], unique=False)
    op.drop_column('tracker_tv_quotes', 'episode_id')
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('tracker_tv_series',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('poster_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('backdrop_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tmdb_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_seasons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_episodes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_air_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_air_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('acquired_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tracker_tv_series_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tracker_tv_series_pkey'))
    )
    op.create_index(op.f('ix_tracker_tv_series_user_id'), 'tracker_tv_series', ['user_id'], unique=False)
    op.create_index(op.f('ix_tracker_tv_series_tmdb_id'), 'tracker_tv_series', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_tracker_tv_series_status'), 'tracker_tv_series', ['status'], unique=False)
    op.create_table('tracker_tv_episodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('episode_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('air_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('watched', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('watched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['tracker_tv_series.id'], name=op.f('tracker_tv_episodes_series_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tracker_tv_episodes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tracker_tv_episodes_pkey'))
    )
    op.create_index(op.f('ix_tracker_tv_episodes_watched'), 'tracker_tv_episodes', ['watched'], unique=False)
    op.create_index(op.f('ix_tracker_tv_episodes_user_id'), 'tracker_tv_episodes', ['user_id'], unique=False)
    op.create_index(op.f('ix_tracker_tv_episodes_series_id'), 'tracker_tv_episodes', ['series_id'], unique=False)
    op.drop_index(op.f('ix_user_episode_tracking_user_id'), table_name='user_episode_tracking')
    op.drop_index(op.f('ix_user_episode_tracking_episode_id'), table_name='user_episode_tracking')
    op.drop_table('user_episode_tracking')
    op.drop_index(op.f('ix_user_series_tracking_user_id'), table_name='user_series_tracking')
    op.drop_index(op.f('ix_user_series_tracking_status'), table_name='user_series_tracking')
    op.drop_index(op.f('ix_user_series_tracking_series_tmdb_id'), table_name='user_series_tracking')
    op.drop_table('user_series_tracking')
    op.drop_index(op.f('ix_tmdb_episodes_series_tmdb_id'), table_name='tmdb_episodes')
    op.drop_table('tmdb_episodes')
    op.drop_table('tmdb_series')
    # ### end Alembic commands ###
