"""Add still_path to tmdb_episodes

Revision ID: 3a87b89f56d8
Revises: c9e47583cd2f
Create Date: 2026-09-27 02:08:42.876035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a87b89f56d8'
down_revision: Union[str, Sequence[str], None] = 'c9e47583cd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    op.add_column('tmdb_series', sa.Column('still_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmdb_series', 'still_path')
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
