"""Refactor UserEpisodeTracking to UserEpisodeLog for Diary pattern

Revision ID: 49954307e44a
Revises: 1a169030e611
Create Date: 2026-09-22 19:38:34.945757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49954307e44a'
down_revision: Union[str, Sequence[str], None] = '1a169030e611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_user_episode_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_visibility', sa.String(length=50), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['tmdb_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tv_user_episode_logs_id'), 'tv_user_episode_logs', ['id'], unique=False)
    op.create_index(op.f('ix_tv_user_episode_logs_user_id'), 'tv_user_episode_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_episode_tracking_episode_id'), table_name='user_episode_tracking')
    op.drop_index(op.f('ix_user_episode_tracking_user_id'), table_name='user_episode_tracking')
    op.drop_table('user_episode_tracking')
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_episode_tracking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_visibility', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('watched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['tmdb_episodes.id'], name=op.f('user_episode_tracking_episode_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_episode_tracking_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_episode_tracking_pkey'))
    )
    op.create_index(op.f('ix_user_episode_tracking_user_id'), 'user_episode_tracking', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_episode_tracking_episode_id'), 'user_episode_tracking', ['episode_id'], unique=False)
    op.drop_index(op.f('ix_tv_user_episode_logs_user_id'), table_name='tv_user_episode_logs')
    op.drop_index(op.f('ix_tv_user_episode_logs_id'), table_name='tv_user_episode_logs')
    op.drop_table('tv_user_episode_logs')
    # ### end Alembic commands ###
