"""Add missing trackers logs tables

Revision ID: 4f099aed880c
Revises: c8a6d18e94b6
Create Date: 2026-09-30 11:07:48.565297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f099aed880c'
down_revision: Union[str, Sequence[str], None] = 'c8a6d18e94b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    op.alter_column('tv_user_series_logs', 'review_visibility',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('tv_user_series_logs', 'watched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('tv_user_series_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('tv_user_series_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_tv_user_series_logs_id'), 'tv_user_series_logs', ['id'], unique=False)
    op.create_index(op.f('ix_tv_user_series_logs_series_tmdb_id'), 'tv_user_series_logs', ['series_tmdb_id'], unique=False)
    op.create_index(op.f('ix_tv_user_series_logs_user_id'), 'tv_user_series_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tv_user_series_logs_user_id'), table_name='tv_user_series_logs')
    op.drop_index(op.f('ix_tv_user_series_logs_series_tmdb_id'), table_name='tv_user_series_logs')
    op.drop_index(op.f('ix_tv_user_series_logs_id'), table_name='tv_user_series_logs')
    op.alter_column('tv_user_series_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('tv_user_series_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('tv_user_series_logs', 'watched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('tv_user_series_logs', 'review_visibility',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'friends_only'::character varying"),
               nullable=True)
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
