"""secondo test

Revision ID: 5b4d913d14f4
Revises: 
Create Date: 2026-07-24 18:13:25.413271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4d913d14f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_daily_entries_one_monthly_goal', 'daily_entries', ['user_id', 'data_riferimento'], unique=True, postgresql_where=sa.text("tipo = 'OM'"))
    op.create_index('ux_daily_entries_one_od_per_day', 'daily_entries', ['user_id', 'data_riferimento'], unique=True, postgresql_where=sa.text("tipo = 'OD'"))
    op.create_index('ux_daily_entries_one_px_per_day', 'daily_entries', ['user_id', 'data_riferimento'], unique=True, postgresql_where=sa.text("tipo = 'PX'"))
    op.create_index('ux_daily_entries_one_weekly_goal', 'daily_entries', ['user_id', 'data_riferimento'], unique=True, postgresql_where=sa.text("tipo = 'OW'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_daily_entries_one_weekly_goal', table_name='daily_entries', postgresql_where=sa.text("tipo = 'OW'"))
    op.drop_index('ux_daily_entries_one_px_per_day', table_name='daily_entries', postgresql_where=sa.text("tipo = 'PX'"))
    op.drop_index('ux_daily_entries_one_od_per_day', table_name='daily_entries', postgresql_where=sa.text("tipo = 'OD'"))
    op.drop_index('ux_daily_entries_one_monthly_goal', table_name='daily_entries', postgresql_where=sa.text("tipo = 'OM'"))
    # ### end Alembic commands ###
