"""add_viewing_platform

Revision ID: a007ba13ba83
Revises: fbc749dd477f
Create Date: 2026-10-03 14:34:27.524351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a007ba13ba83'
down_revision: Union[str, Sequence[str], None] = 'fbc749dd477f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_product_brands_brand_id'), table_name='shopping_product_brands')
    op.drop_index(op.f('ix_shopping_product_brands_product_id'), table_name='shopping_product_brands')
    op.drop_table('shopping_product_brands')
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    op.add_column('tv_user_series_logs', sa.Column('viewing_platform', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_user_series_logs', 'viewing_platform')
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('shopping_product_brands',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['shopping_suppliers.id'], name=op.f('shopping_product_brands_brand_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['shopping_products.id'], name=op.f('shopping_product_brands_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shopping_product_brands_pkey')),
    sa.UniqueConstraint('product_id', 'brand_id', name=op.f('uq_shopping_product_brands'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shopping_product_brands_product_id'), 'shopping_product_brands', ['product_id'], unique=False)
    op.create_index(op.f('ix_shopping_product_brands_brand_id'), 'shopping_product_brands', ['brand_id'], unique=False)
    # ### end Alembic commands ###
