"""add_tracker_fields

Revision ID: a282ff0494d6
Revises: 047f9fbf7030
Create Date: 2026-09-18 01:23:09.489197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a282ff0494d6'
down_revision: Union[str, Sequence[str], None] = '047f9fbf7030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_tv_series', sa.Column('acquired_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('tv_episodes_yearly_goal', sa.Integer(), server_default=sa.text('300'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tv_episodes_yearly_goal')
    op.drop_column('tracker_tv_series', 'acquired_date')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
