"""Add MediaList models

Revision ID: c9e47583cd2f
Revises: 17c037efa957
Create Date: 2026-09-26 18:32:10.669790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e47583cd2f'
down_revision: Union[str, Sequence[str], None] = '17c037efa957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_lists_user_id'), 'media_lists', ['user_id'], unique=False)
    op.create_table('media_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('series_tmdb_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['media_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_tmdb_id'], ['tmdb_series.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_list_items_list_id'), 'media_list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_media_list_items_series_tmdb_id'), 'media_list_items', ['series_tmdb_id'], unique=False)
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_media_list_items_series_tmdb_id'), table_name='media_list_items')
    op.drop_index(op.f('ix_media_list_items_list_id'), table_name='media_list_items')
    op.drop_table('media_list_items')
    op.drop_index(op.f('ix_media_lists_user_id'), table_name='media_lists')
    op.drop_table('media_lists')
    # ### end Alembic commands ###
