"""Add UserYearlyGoal and remove tv_episodes_yearly_goal from User

Revision ID: fbc749dd477f
Revises: 25fcf29afbe7
Create Date: 2026-10-01 19:59:12.820588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc749dd477f'
down_revision: Union[str, Sequence[str], None] = '25fcf29afbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_yearly_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tracker_type', sa.String(length=50), nullable=False),
    sa.Column('goal_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'tracker_type', name='ux_user_year_tracker')
    )
    op.create_index(op.f('ix_user_yearly_goals_user_id'), 'user_yearly_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_yearly_goals_year'), 'user_yearly_goals', ['year'], unique=False)
    op.drop_column('users', 'tv_episodes_yearly_goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tv_episodes_yearly_goal', sa.INTEGER(), server_default=sa.text('300'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_yearly_goals_year'), table_name='user_yearly_goals')
    op.drop_index(op.f('ix_user_yearly_goals_user_id'), table_name='user_yearly_goals')
    op.drop_table('user_yearly_goals')
    # ### end Alembic commands ###
