from typing import Final


BOOT_STATUS_EMPTY: Final[str] = "EMPTY"
BOOT_STATUS_LEGACY_SCHEMA_DETECTED: Final[str] = "LEGACY_SCHEMA_DETECTED"
BOOT_STATUS_SUPERUSER_REQUIRED: Final[str] = "SUPERUSER_REQUIRED"
BOOT_STATUS_SUPERUSER_PASSWORD_CHANGE_REQUIRED: Final[str] = "SUPERUSER_PASSWORD_CHANGE_REQUIRED"
BOOT_STATUS_READY: Final[str] = "READY"
BOOT_STATUS_ERROR: Final[str] = "ERROR"
